NAME = megaphone

CC = c++

CFLAGS = -Wall -Wextra -Werror

SRCS = megaphone.cpp


all :
		$(CC) $(CFLAGS) $(SRCS) -o  $(NAME)

clean :
		rm -rf *.o

fclean : clean
		rm -rf $(NAME)

re : fclean all
		